provider:
  name: aws
env:
  - name: AWS_DEFAULT_REGION
    value: us-east-1

domainFilters: ["1uphealthdev2.com"]

triggerLoopOnEvent: true
interval: 24h
extraArgs:
  - "--aws-zone-type=public"
  - "--aws-zones-cache-duration=1h"
txtOwnerId: external-dns

