# TODO: Keycloak secrets are key-value pairs rather than just values
# https://external-secrets.io/latest/guides/all-keys-one-secret/
# secrets:
#   keycloakConfig:
#     targetNamespace: core-infra
#     secretName: keycloak-config
#     keys:    
#       - secretKey: admin_username
#         remoteRef: ""
#       - secretKey: admin_password
#         remoteRef: ""
#       - secretKey: smtp_username
#         remoteRef: ""
#       - secretKey: smtp_password
#         remoteRef: ""
#       - secretKey: jdbc_url
#         remoteRef: ""

ssmParameters:
  keycloakConfig:
    targetNamespace: core-infra
    secretName: keycloak-config
    keys:
      - secretKey: admin_username
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/KEYCLOAK_ADMIN_USERNAME"
      - secretKey: admin_password
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/KEYCLOAK_ADMIN_PASSWORD"
      - secretKey: jdbc_url
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/KEYCLOAK_JDBC_URL"
      # - secretKey: smtp_username
        #   remoteRef: "REPLACE_WITH_REAL_VALUE"
      # - secretKey: smtp_password
        #  remoteRef: "REPLACE_WITH_REAL_VALUE"
  coreInfraGatewayConfig:
    targetNamespace: core-infra
    secretName: core-infra-gateway-config
    keys:
      - secretKey: readonly_db_connection_string
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/DB_READONLY_CONNECTION_STRING"
      - secretKey: encryption_secret
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/ENCRYPTION_SECRET" 
      - secretKey: keycloak_uri
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/KEYCLOAK_URI" 
      - secretKey: request_token_client_id
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/REQUEST_TOKEN_CLIENT_ID"
      - secretKey: request_token_client_secret
        remoteRef: "arn:aws:ssm:us-east-1:738897926653:parameter/core-infra/REQUEST_TOKEN_CLIENT_SECRET"
        
